package view;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import controller.ControllerParkingControl;
import i18N.Local;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;




/**
 *
 * @author FabioDelaRoca
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    String lingua = "pt";
    String pais = "BR";
    Local local = new Local(lingua, pais);
    private ResourceBundle textos = local.getBundle();

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        btRegistrarCobranca.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbParkingControl = new javax.swing.JLabel();
        pnCobranca = new javax.swing.JPanel();
        btRegistrarCobranca = new javax.swing.JButton();
        lbCobranca = new javax.swing.JLabel();
        pnDadosRegistro = new javax.swing.JPanel();
        lbPlacaLabel = new javax.swing.JLabel();
        lbPlacaRegistrada = new javax.swing.JLabel();
        lbEntradaLabel = new javax.swing.JLabel();
        lbEntradaRegistrada = new javax.swing.JLabel();
        lbSaidaLabel = new javax.swing.JLabel();
        lbSaidaRegistrada = new javax.swing.JLabel();
        lbValorLabel = new javax.swing.JLabel();
        lbValorACobrar = new javax.swing.JLabel();
        pnGanhos = new javax.swing.JPanel();
        pnPlacaHorario = new javax.swing.JPanel();
        lbPlaca = new javax.swing.JLabel();
        txfPlaca = new javax.swing.JFormattedTextField();
        lbHora = new javax.swing.JLabel();
        spHora = new javax.swing.JSpinner();
        spMinuto = new javax.swing.JSpinner();
        lbMinuto = new javax.swing.JLabel();
        pnSaida = new javax.swing.JPanel();
        lbSaida = new javax.swing.JLabel();
        btRegistrarSaida = new javax.swing.JButton();
        pnAtributosCobranca = new javax.swing.JPanel();
        lbPeriodoInicial = new javax.swing.JLabel();
        spPeriodoInicial = new javax.swing.JSpinner();
        lbTolerancia = new javax.swing.JLabel();
        spTolerancia = new javax.swing.JSpinner();
        lbPeriodoAdicional = new javax.swing.JLabel();
        spPeriodoAdicional = new javax.swing.JSpinner();
        lbValorInicial = new javax.swing.JLabel();
        txValorInicial = new java.awt.TextField();
        lbValorAdicional = new javax.swing.JLabel();
        txValorAdicional = new java.awt.TextField();
        pnEntrada = new javax.swing.JPanel();
        lbEntrada = new javax.swing.JLabel();
        btRegistrarEntrada = new javax.swing.JButton();
        btIdiomaEng = new javax.swing.JButton();
        btIdiomaPtBr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(textos.getString("PARKINGCONTROL")); // NOI18N

        lbParkingControl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbParkingControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbParkingControl.setText(textos.getString("PARKING CONTROL")); // NOI18N

        pnCobranca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnCobranca.setLayout(new java.awt.BorderLayout(12, 10));

        btRegistrarCobranca.setText(textos.getString("REGISTRAR COBRANÇA")); // NOI18N
        btRegistrarCobranca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarCobrancaActionPerformed(evt);
            }
        });
        pnCobranca.add(btRegistrarCobranca, java.awt.BorderLayout.PAGE_END);

        lbCobranca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCobranca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCobranca.setText(textos.getString("COBRANÇA")); // NOI18N
        lbCobranca.setToolTipText("");
        pnCobranca.add(lbCobranca, java.awt.BorderLayout.PAGE_START);

        pnDadosRegistro.setMinimumSize(new java.awt.Dimension(90, 88));
        pnDadosRegistro.setPreferredSize(new java.awt.Dimension(90, 88));
        pnDadosRegistro.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        lbPlacaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPlacaLabel.setText(textos.getString("PLACA: ")); // NOI18N
        pnDadosRegistro.add(lbPlacaLabel);

        lbPlacaRegistrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbPlacaRegistrada.setText("XXX-XXXX");
        pnDadosRegistro.add(lbPlacaRegistrada);

        lbEntradaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbEntradaLabel.setText(textos.getString("ENTRADA:")); // NOI18N
        pnDadosRegistro.add(lbEntradaLabel);

        lbEntradaRegistrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEntradaRegistrada.setText("HH:MM");
        pnDadosRegistro.add(lbEntradaRegistrada);

        lbSaidaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSaidaLabel.setText(textos.getString("SAÍDA:")); // NOI18N
        pnDadosRegistro.add(lbSaidaLabel);

        lbSaidaRegistrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSaidaRegistrada.setText("HH:MM");
        pnDadosRegistro.add(lbSaidaRegistrada);

        lbValorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValorLabel.setText(textos.getString("VALOR(R$):")); // NOI18N
        pnDadosRegistro.add(lbValorLabel);

        lbValorACobrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbValorACobrar.setText(textos.getString("0,00")); // NOI18N
        pnDadosRegistro.add(lbValorACobrar);

        pnCobranca.add(pnDadosRegistro, java.awt.BorderLayout.CENTER);

        pnPlacaHorario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPlaca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPlaca.setText(textos.getString("PLACA")); // NOI18N

        txfPlaca.setColumns(7);
        try {
            txfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbHora.setText(textos.getString(" HORAS")); // NOI18N

        spHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        spHora.setPreferredSize(new java.awt.Dimension(40, 20));

        spMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        spMinuto.setPreferredSize(new java.awt.Dimension(40, 20));

        lbMinuto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbMinuto.setText(textos.getString("MINUTOS")); // NOI18N

        pnSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnSaida.setLayout(new java.awt.BorderLayout(10, 10));

        lbSaida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSaida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSaida.setText(textos.getString("SAÍDA")); // NOI18N
        lbSaida.setToolTipText("");
        pnSaida.add(lbSaida, java.awt.BorderLayout.PAGE_START);

        btRegistrarSaida.setText(textos.getString("REGISTRAR SAÍDA")); // NOI18N
        btRegistrarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarSaidaActionPerformed(evt);
            }
        });
        pnSaida.add(btRegistrarSaida, java.awt.BorderLayout.PAGE_END);

        pnAtributosCobranca.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        lbPeriodoInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPeriodoInicial.setText(textos.getString("PERÍODO INICIAL:")); // NOI18N
        lbPeriodoInicial.setToolTipText("Período em que será cobrado uma vez, passando dele, será adicionado ao custo o valor do \"Período Adicional\"");
        pnAtributosCobranca.add(lbPeriodoInicial);

        spPeriodoInicial.setModel(new javax.swing.SpinnerNumberModel(2, 0, 24, 1));
        spPeriodoInicial.setToolTipText(textos.getString("HORAS")); // NOI18N
        pnAtributosCobranca.add(spPeriodoInicial);

        lbTolerancia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTolerancia.setText(textos.getString("TOLERÂNCIA:")); // NOI18N
        lbTolerancia.setToolTipText(textos.getString("PERMANÊNCIA EM QUE NÃO SERÁ COBRADO")); // NOI18N
        pnAtributosCobranca.add(lbTolerancia);

        spTolerancia.setModel(new javax.swing.SpinnerNumberModel(15, 0, 1440, 1));
        spTolerancia.setToolTipText(textos.getString("MINUTOS")); // NOI18N
        pnAtributosCobranca.add(spTolerancia);

        lbPeriodoAdicional.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPeriodoAdicional.setText(textos.getString("PERÍODO ADICIONAL:")); // NOI18N
        lbPeriodoAdicional.setToolTipText(textos.getString("PERÍODO EM QUE SERÁ COBRADO ADICIONALMENTE")); // NOI18N
        pnAtributosCobranca.add(lbPeriodoAdicional);

        spPeriodoAdicional.setModel(new javax.swing.SpinnerNumberModel(1, 0, 24, 1));
        spPeriodoAdicional.setToolTipText(textos.getString("HORAS")); // NOI18N
        pnAtributosCobranca.add(spPeriodoAdicional);

        lbValorInicial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValorInicial.setText(textos.getString("VALOR INICIAL:")); // NOI18N
        lbValorInicial.setToolTipText(textos.getString("VALOR COBRADO PELO PERÍODO INICIAL")); // NOI18N
        pnAtributosCobranca.add(lbValorInicial);

        txValorInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txValorInicial.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txValorInicial.setMinimumSize(new java.awt.Dimension(35, 25));
        txValorInicial.setText(textos.getString("10,00")); // NOI18N
        pnAtributosCobranca.add(txValorInicial);
        txValorInicial.getAccessibleContext().setAccessibleName(textos.getString("VALOR INICIAL:")); // NOI18N
        txValorInicial.getAccessibleContext().setAccessibleDescription(textos.getString("VALOR COBRADO PELO PERÍODO INICIAL DO ESTACIONAMENTO")); // NOI18N

        lbValorAdicional.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValorAdicional.setText(textos.getString("VALOR ADICIONAL:")); // NOI18N
        lbValorAdicional.setToolTipText(textos.getString("VALOR COBRADO PELO PERÍODO ADICIONAL")); // NOI18N
        pnAtributosCobranca.add(lbValorAdicional);

        txValorAdicional.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txValorAdicional.setMinimumSize(new java.awt.Dimension(29, 30));
        txValorAdicional.setText(textos.getString("7,00")); // NOI18N
        pnAtributosCobranca.add(txValorAdicional);
        txValorAdicional.getAccessibleContext().setAccessibleName(textos.getString("VALOR ADICIONAL:")); // NOI18N
        txValorAdicional.getAccessibleContext().setAccessibleDescription(textos.getString("VALOR COBRADO PELO PERÍODO ADICIONAL")); // NOI18N

        pnSaida.add(pnAtributosCobranca, java.awt.BorderLayout.CENTER);

        pnEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnEntrada.setLayout(new java.awt.BorderLayout(10, 10));

        lbEntrada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEntrada.setText(textos.getString("ENTRADA")); // NOI18N
        lbEntrada.setToolTipText("");
        pnEntrada.add(lbEntrada, java.awt.BorderLayout.CENTER);

        btRegistrarEntrada.setText(textos.getString("REGISTRAR ENTRADA")); // NOI18N
        btRegistrarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarEntradaActionPerformed(evt);
            }
        });
        pnEntrada.add(btRegistrarEntrada, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnPlacaHorarioLayout = new javax.swing.GroupLayout(pnPlacaHorario);
        pnPlacaHorario.setLayout(pnPlacaHorarioLayout);
        pnPlacaHorarioLayout.setHorizontalGroup(
            pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPlacaHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPlacaHorarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPlaca))
                        .addGap(18, 18, 18)
                        .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPlacaHorarioLayout.createSequentialGroup()
                                .addComponent(spHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(pnPlacaHorarioLayout.createSequentialGroup()
                                .addComponent(lbHora)
                                .addGap(24, 24, 24)))
                        .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMinuto))
                        .addGap(33, 33, 33))
                    .addComponent(pnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnPlacaHorarioLayout.setVerticalGroup(
            pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPlacaHorarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPlaca)
                    .addComponent(lbMinuto)
                    .addComponent(lbHora))
                .addGap(1, 1, 1)
                .addGroup(pnPlacaHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        btIdiomaEng.setActionCommand("btIdiomaEng");
        btIdiomaEng.setLabel("ENG");
        btIdiomaEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdiomaEngActionPerformed(evt);
            }
        });

        btIdiomaPtBr.setText("BR");
        btIdiomaPtBr.setActionCommand("btIdiomaPtBr");
        btIdiomaPtBr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIdiomaPtBrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbParkingControl, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnPlacaHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btIdiomaPtBr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btIdiomaEng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pnGanhos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbParkingControl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btIdiomaPtBr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIdiomaEng)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(pnPlacaHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btIdiomaEng.getAccessibleContext().setAccessibleName("btIdiomaEng");
        btIdiomaPtBr.getAccessibleContext().setAccessibleName("btIdiomaPtBr");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarSaidaActionPerformed
    String placa = (String)txfPlaca.getValue();
    if (placa == null){
        JOptionPane.showMessageDialog(new JFrame(), textos.getString("INFORME A PLACA"), textos.getString("ERRO!"),JOptionPane.ERROR_MESSAGE);
    } else {
        String resultado = controller.ControllerParkingControl.RegistrarSaida(placa, (Integer) spHora.getValue(), (Integer) spMinuto.getValue(), (Integer) spPeriodoInicial.getValue(), (Integer) spPeriodoAdicional.getValue(), Double.parseDouble(txValorInicial.getText().replace(textos.getString(","), textos.getString("."))), Double.parseDouble(txValorAdicional.getText().replace(textos.getString(","), textos.getString("."))), (Integer) spTolerancia.getValue());
        if (resultado.equals("false1")){
            JOptionPane.showMessageDialog(new JFrame(), textos.getString("PLACA INEXISTENTE NO ESTACIONAMENTO"), textos.getString("ERRO!"),JOptionPane.ERROR_MESSAGE);
        } else if (resultado.equals("false2")){
            JOptionPane.showMessageDialog(new JFrame(), textos.getString("REGISTRO DE HORA DE SAÍDA INCORRETO"), textos.getString("ERRO!"),JOptionPane.ERROR_MESSAGE);
        } else {
            String[] cobrancas = resultado.split(";");
            lbPlacaRegistrada.setText(placa);
            lbEntradaRegistrada.setText(String.valueOf(cobrancas[0]));
            lbSaidaRegistrada.setText(String.valueOf(cobrancas[1]));
            lbValorACobrar.setText(String.valueOf(cobrancas[2]));
            lbPlacaRegistrada.repaint();
            lbEntradaRegistrada.repaint();
            lbSaidaRegistrada.repaint();
            lbValorACobrar.repaint();
            btRegistrarCobranca.setEnabled(true);
            btRegistrarEntrada.setEnabled(false);
            btRegistrarSaida.setEnabled(false);
            JOptionPane.showMessageDialog(new JFrame(), textos.getString("REGISTRADO A SAÍDA. VERIFIQUE AO LADO OS DADOS E O VALOR DA COBRANÇA"), textos.getString("SUCESSO"), JOptionPane.INFORMATION_MESSAGE);
        }
    }

    }//GEN-LAST:event_btRegistrarSaidaActionPerformed

    private void btRegistrarCobrancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarCobrancaActionPerformed
        controller.ControllerParkingControl.RegistrarCobranca(lbPlacaRegistrada.getText().replace("-", ""));
        lbPlacaRegistrada.setText("XXX-XXXX");
        lbEntradaRegistrada.setText("HH:MM");
        lbSaidaRegistrada.setText("HH:MM");
        lbValorACobrar.setText(textos.getString("0,00"));
        lbPlacaRegistrada.repaint();
        lbEntradaRegistrada.repaint();
        lbSaidaRegistrada.repaint();
        lbValorACobrar.repaint();
        btRegistrarCobranca.setEnabled(false);
        btRegistrarEntrada.setEnabled(true);
        btRegistrarSaida.setEnabled(true);
        JOptionPane.showMessageDialog(new JFrame(), textos.getString("COBRANÇA REALIZADO COM SUCESSO"), textos.getString("SUCESSO"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btRegistrarCobrancaActionPerformed

    private void btRegistrarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarEntradaActionPerformed
        String placa = (String)txfPlaca.getValue();
        if (placa == null){
            JOptionPane.showMessageDialog(new JFrame(), textos.getString("INFORME A PLACA"), textos.getString("ERRO!"),JOptionPane.ERROR_MESSAGE);
        } else {
            Integer valorHora = (Integer)spHora.getValue();
            Integer valorMinutos = (Integer)spMinuto.getValue();
            if(controller.ControllerParkingControl.RegistrarEntrada(placa, valorHora, valorMinutos)) {
                JOptionPane.showMessageDialog(new JFrame(), textos.getString("ENTRADA REGISTRADO COM SUCESSO"), textos.getString("SUCESSO"), JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), textos.getString("PLACA EXISTENTE NO ESTACIONAMENTO"), textos.getString("ERRO!"),JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btRegistrarEntradaActionPerformed

    private void btIdiomaEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdiomaEngActionPerformed
        lingua = "en";
	pais = "US";
        local.setLocal(lingua, pais);
        textos = local.getBundle();
        this.lbSaida.repaint();
    }//GEN-LAST:event_btIdiomaEngActionPerformed

    private void btIdiomaPtBrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIdiomaPtBrActionPerformed
        lingua = "pt";
        pais = "BR";
        local.setLocal(lingua, pais);
        textos = local.getBundle();
        this.initComponents();
    }//GEN-LAST:event_btIdiomaPtBrActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIdiomaEng;
    private javax.swing.JButton btIdiomaPtBr;
    private javax.swing.JButton btRegistrarCobranca;
    private javax.swing.JButton btRegistrarEntrada;
    private javax.swing.JButton btRegistrarSaida;
    private javax.swing.JLabel lbCobranca;
    private javax.swing.JLabel lbEntrada;
    private javax.swing.JLabel lbEntradaLabel;
    private javax.swing.JLabel lbEntradaRegistrada;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbMinuto;
    private javax.swing.JLabel lbParkingControl;
    private javax.swing.JLabel lbPeriodoAdicional;
    private javax.swing.JLabel lbPeriodoInicial;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbPlacaLabel;
    private javax.swing.JLabel lbPlacaRegistrada;
    private javax.swing.JLabel lbSaida;
    private javax.swing.JLabel lbSaidaLabel;
    private javax.swing.JLabel lbSaidaRegistrada;
    private javax.swing.JLabel lbTolerancia;
    private javax.swing.JLabel lbValorACobrar;
    private javax.swing.JLabel lbValorAdicional;
    private javax.swing.JLabel lbValorInicial;
    private javax.swing.JLabel lbValorLabel;
    private javax.swing.JPanel pnAtributosCobranca;
    private javax.swing.JPanel pnCobranca;
    private javax.swing.JPanel pnDadosRegistro;
    private javax.swing.JPanel pnEntrada;
    private javax.swing.JPanel pnGanhos;
    private javax.swing.JPanel pnPlacaHorario;
    private javax.swing.JPanel pnSaida;
    private javax.swing.JSpinner spHora;
    private javax.swing.JSpinner spMinuto;
    private javax.swing.JSpinner spPeriodoAdicional;
    private javax.swing.JSpinner spPeriodoInicial;
    private javax.swing.JSpinner spTolerancia;
    private java.awt.TextField txValorAdicional;
    private java.awt.TextField txValorInicial;
    private javax.swing.JFormattedTextField txfPlaca;
    // End of variables declaration//GEN-END:variables
}
